### ISSUE TITLE
How to parse local JSON into a variable in javascript?

### ISSUE THREAD

**Issue by leoscku** [tngoon/icritiquekit#19]
This is what I'm using right now:
  var request = new XMLHttpRequest();
   request.open("GET", "../json/StudentList.JSON", false);
   request.send(null)
   var studentList = JSON.parse(request.responseText);

But I still couldn't parse the JSON file, what can i do?

**Comment by ailiefraser** [comment]
if you are using node.js, you can read in JSON on the server using require. For example line 35 in https://github.com/DesignAtLarge/critiquekit/blob/master/server.js: `var comment_obj = require('./original_comments.json');`

**Comment by leoscku** [comment]
I tried using that, but I just keep getting this error: `ReferenceError: Can't find variable: require`

**Comment by ailiefraser** [comment]
Where are you trying this? It has to be in server.js, and node has to be running.

**Comment by leoscku** [comment]
I'm running it in another js file, I was trying to create a dummy JSON file to import a list of students, extracting the individual TA ID and only display the students that correspond to that TA

**Comment by ailiefraser** [comment]
you can only read in JSON files from the server (because other js files run on the user's browser, so they won't have access to those files). So what you should do is have your other js file send a socket message to the server asking it to load the file, then when the server gets that message it can load the json with require and send the object back to your js file in a socket message. 

For an example, see how https://github.com/DesignAtLarge/critiquekit/blob/master/public/js/main.js emits a 'get saved' message on line 858, and in https://github.com/DesignAtLarge/critiquekit/blob/master/server.js on line 279 it receives that message and sends back the desired data (which was loaded earlier with require).

**Comment by leoscku** [comment]
I will look into it, thank you!

**Comment by leoscku** [comment]
I'm still confused, right now in server.js I have:
`var studentList = require('../json/StudentList.JSON');`
`socket.on('requestStudentList', function(data)){
  }`

And in TALanding.js I have:
`socket.emit('requestStudentList', studentList);`

What do I need in order to get the `../json/StudentList.JSON` file into TALanding.js as a variable so I can conduct functions with it?

**Comment by ailiefraser** [comment]
server.js should have something like
`var studentList = require('../json/StudentList.JSON');`
`socket.on('requestStudentList', function() {
    socket.emit('studentList', studentList);
});`

and TALanding.js should have
`socket.emit('requestStudentList');`
`socket.on('studentList', function(data) {`
`    studentList = data;`
`    // do whatever you need to do with studentList`
`});`

**Comment by leoscku** [comment]
I did as you said, but now I encounter the error `Error: Cannot find module './json/StudentList.JSON'`

StudentList.JSON is located in a folder `json`, which the folder is the same level as server.js

**Comment by ailiefraser** [comment]
I think you need to either keep the json file in the root folder (not in a json folder), or add something like `.use(express.static(__dirname + '/json'))` after line 17

**Comment by leoscku** [comment]
I tried both, but still can’t get it to work. Is there any other way to do this?

**Comment by ailiefraser** [comment]
is your code on github? if not, can you commit it so I can take a look?

**Comment by leoscku** [comment]
I just committed to my branch

**Comment by ailiefraser** [comment]
the file extension needs to be lowercase.
I got it working with `var studentList = require('./studentList.json');`

**Comment by leoscku** [comment]
After doing that, I now get this error in `ReferenceError: Can't find variable: socket`, which points to this line of code`socket.emit('requestStudentList');` in `TALanding.js`
